/* tslint:disable */
/* eslint-disable */
/**
 * BFF API
 * Backend For Frontend API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AnnotatedItemPaid } from './annotated-item-paid';

/**
 * 
 * @export
 * @interface AnnotatedMonsieurAxelMenvoie2
 */
export interface AnnotatedMonsieurAxelMenvoie2 {
    /**
     * 
     * @type {{ [key: string]: Array<AnnotatedItemPaid>; }}
     * @memberof AnnotatedMonsieurAxelMenvoie2
     */
    'elementToBePaid': { [key: string]: Array<AnnotatedItemPaid>; };
    /**
     * 
     * @type {string}
     * @memberof AnnotatedMonsieurAxelMenvoie2
     */
    'groupId': string;
}

