/* tslint:disable */
/* eslint-disable */
/**
 * BFF API
 * Backend For Frontend API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AnnotatedOffer
 */
export interface AnnotatedOffer {
    /**
     * 
     * @type {Array<string>}
     * @memberof AnnotatedOffer
     */
    'availableItems': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AnnotatedOffer
     */
    'name': string;
}

