/* tslint:disable */
/* eslint-disable */
/**
 * BFF API
 * Backend For Frontend API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AnnotatedTableWithOrderDto
 */
export interface AnnotatedTableWithOrderDto {
    /**
     * 
     * @type {string}
     * @memberof AnnotatedTableWithOrderDto
     */
    '_id': string;
    /**
     * 
     * @type {number}
     * @memberof AnnotatedTableWithOrderDto
     */
    'number': number;
    /**
     * 
     * @type {string}
     * @memberof AnnotatedTableWithOrderDto
     */
    'tableOrderId': string;
    /**
     * 
     * @type {boolean}
     * @memberof AnnotatedTableWithOrderDto
     */
    'taken': boolean;
}

