/* tslint:disable */
/* eslint-disable */
/**
 * BFF API
 * Backend For Frontend API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AnnotatedItemPaid
 */
export interface AnnotatedItemPaid {
    /**
     * 
     * @type {string}
     * @memberof AnnotatedItemPaid
     */
    'itemId': string;
    /**
     * 
     * @type {number}
     * @memberof AnnotatedItemPaid
     */
    'quantityPaid': number;
}

