/* tslint:disable */
/* eslint-disable */
/**
 * BFF API
 * Backend For Frontend API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MenuItemDto
 */
export interface MenuItemDto {
    /**
     * 
     * @type {string}
     * @memberof MenuItemDto
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof MenuItemDto
     */
    'fullName': string;
    /**
     * 
     * @type {string}
     * @memberof MenuItemDto
     */
    'shortName': string;
    /**
     * 
     * @type {number}
     * @memberof MenuItemDto
     */
    'price': number;
    /**
     * 
     * @type {string}
     * @memberof MenuItemDto
     */
    'category': MenuItemDtoCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof MenuItemDto
     */
    'image': string;
}

export const MenuItemDtoCategoryEnum = {
    Starter: 'STARTER',
    Main: 'MAIN',
    Dessert: 'DESSERT',
    Beverage: 'BEVERAGE'
} as const;

export type MenuItemDtoCategoryEnum = typeof MenuItemDtoCategoryEnum[keyof typeof MenuItemDtoCategoryEnum];


