apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/spos/frontend-workflow
    newName: ghcr.io/startupnationlabs/spos/frontend-workflow
    newTag: sha-b1cabce

patches:
  - target:
      kind: Ingress
      name: ingress
    path: ingress-patch.yml
