/* tslint:disable */
/* eslint-disable */
/**
 * BFF API
 * Backend For Frontend API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/default-api';
export * from './api/remote-catalogue-api';
export * from './api/remote-group-api';
export * from './api/remote-kitchen-api';
export * from './api/remote-offer-api';
export * from './api/remote-table-api';

