services:
  frontend-bff:
    build:
      context: .
      dockerfile: ./apps/frontend-bff/Dockerfile
    ports:
      - 3000:80
  frontend-workflow:
    build:
      context: .
      dockerfile: ./apps/frontend-workflow/Dockerfile
    ports:
      - 3001:80
  backend-bff:
    build:
      context: .
      dockerfile: ./apps/backend-bff/Dockerfile
    ports:
      - 3002:3000
  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
