/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Menu Service
 * Menu Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddMenuItemDto
 */
export interface AddMenuItemDto {
    /**
     * 
     * @type {string}
     * @memberof AddMenuItemDto
     */
    'fullName': string;
    /**
     * 
     * @type {string}
     * @memberof AddMenuItemDto
     */
    'shortName': string;
    /**
     * 
     * @type {number}
     * @memberof AddMenuItemDto
     */
    'price': number;
    /**
     * 
     * @type {string}
     * @memberof AddMenuItemDto
     */
    'category': AddMenuItemDtoCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof AddMenuItemDto
     */
    'image': string;
}

export const AddMenuItemDtoCategoryEnum = {
    Starter: 'STARTER',
    Main: 'MAIN',
    Dessert: 'DESSERT',
    Beverage: 'BEVERAGE'
} as const;

export type AddMenuItemDtoCategoryEnum = typeof AddMenuItemDtoCategoryEnum[keyof typeof AddMenuItemDtoCategoryEnum];


