apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/spos/payment-sharing
    newName: ghcr.io/startupnationlabs/spos/payment-sharing
    newTag: sha-136f400


patches:
  - target:
      kind: Ingress
      name: ingress-payment-sharing
    path: ingress-patch.yml
