apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/spos/payment-sharing
    newName: ghcr.io/startupnationlabs/spos/payment-sharing
    newTag: sha-0d870a9


patches:
  - target:
      kind: Ingress
      name: ingress-payment-sharing
    path: ingress-patch.yml
  - target:
      kind: Deployment
      name: payment-sharing
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: http://backend-bff.spos-dev.svc.cluster.local:3000
