/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Kitchen Service
 * Kitchen Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ItemToBeCookedDto
 */
export interface ItemToBeCookedDto {
    /**
     * 
     * @type {string}
     * @memberof ItemToBeCookedDto
     */
    'menuItemShortName': string;
    /**
     * 
     * @type {number}
     * @memberof ItemToBeCookedDto
     */
    'howMany': number;
}

