/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Kitchen Service
 * Kitchen Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Recipe } from './recipe';

/**
 * 
 * @export
 * @interface PreparedItem
 */
export interface PreparedItem {
    /**
     * 
     * @type {string}
     * @memberof PreparedItem
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof PreparedItem
     */
    'shortName': string;
    /**
     * 
     * @type {Recipe}
     * @memberof PreparedItem
     */
    'recipe': Recipe;
    /**
     * 
     * @type {string}
     * @memberof PreparedItem
     */
    'shouldStartAt': string;
    /**
     * 
     * @type {string}
     * @memberof PreparedItem
     */
    'startedAt': string;
    /**
     * 
     * @type {string}
     * @memberof PreparedItem
     */
    'finishedAt': string;
}

