/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Kitchen Service
 * Kitchen Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PreparedItemDto
 */
export interface PreparedItemDto {
    /**
     * 
     * @type {string}
     * @memberof PreparedItemDto
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof PreparedItemDto
     */
    'shortName': string;
    /**
     * 
     * @type {string}
     * @memberof PreparedItemDto
     */
    'shouldStartAt': string;
    /**
     * 
     * @type {string}
     * @memberof PreparedItemDto
     */
    'startedAt': string;
    /**
     * 
     * @type {string}
     * @memberof PreparedItemDto
     */
    'finishedAt': string;
}

