/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Kitchen Service
 * Kitchen Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ItemToBeCookedDto } from './item-to-be-cooked-dto';

/**
 * 
 * @export
 * @interface PreparationRequestDto
 */
export interface PreparationRequestDto {
    /**
     * 
     * @type {number}
     * @memberof PreparationRequestDto
     */
    'tableNumber': number;
    /**
     * 
     * @type {Array<ItemToBeCookedDto>}
     * @memberof PreparationRequestDto
     */
    'itemsToBeCooked': Array<ItemToBeCookedDto>;
}

