/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Kitchen Service
 * Kitchen Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Recipe
 */
export interface Recipe {
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    'shortName': string;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    'post': RecipePostEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Recipe
     */
    'cookingSteps': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Recipe
     */
    'meanCookingTimeInSec': number;
}

export const RecipePostEnum = {
    Bar: 'BAR',
    ColdDish: 'COLD_DISH',
    HotDish: 'HOT_DISH'
} as const;

export type RecipePostEnum = typeof RecipePostEnum[keyof typeof RecipePostEnum];


