/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Kitchen Service
 * Kitchen Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WrongQueryParameterException
 */
export interface WrongQueryParameterException {
    /**
     * 
     * @type {string}
     * @memberof WrongQueryParameterException
     */
    'error': string;
    /**
     * 
     * @type {string}
     * @memberof WrongQueryParameterException
     */
    'details': string;
}

