apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend-bff
  name: backend-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-bff
  template:
    metadata:
      labels:
        io.kompose.service: backend-bff
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/spos/backend-bff:sha-e6b0fb9
          name: backend-bff
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: KITCHEN_BASE_URL
              value: "http://kitchen-backend.spos-prod.svc.cluster.local:3000"
            - name: MENU_BASE_URL
              value: "http://menu-backend.spos-prod.svc.cluster.local:3000"
            - name: DINING_BASE_URL
              value: "http://dining-backend.spos-prod.svc.cluster.local:3000"
            - name: OTLP_URL
              value: "http://jaeger-collector.spos-prod.svc.cluster.local:4318/v1/traces"
            - name: ORDERING_BASE_URL
              value: "http://ordering:3003"
      restartPolicy: Always
