apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
  - infrastructure/traefik
  - apps/spos/develop
  - apps/spos/main

patches:
  - target:
      kind: Ingress
    path: ingress-patch.yml