/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Dining Service
 * Dining Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddMenuItemDto
 */
export interface AddMenuItemDto {
    /**
     * 
     * @type {string}
     * @memberof AddMenuItemDto
     */
    'menuItemId': string;
    /**
     * 
     * @type {string}
     * @memberof AddMenuItemDto
     */
    'menuItemShortName': string;
    /**
     * 
     * @type {number}
     * @memberof AddMenuItemDto
     */
    'howMany': number;
}

