/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Dining Service
 * Dining Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderingItem } from './ordering-item';

/**
 * 
 * @export
 * @interface OrderingLine
 */
export interface OrderingLine {
    /**
     * 
     * @type {OrderingItem}
     * @memberof OrderingLine
     */
    'item': OrderingItem;
    /**
     * 
     * @type {number}
     * @memberof OrderingLine
     */
    'howMany': number;
    /**
     * 
     * @type {boolean}
     * @memberof OrderingLine
     */
    'sentForPreparation': boolean;
}

