/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Dining Service
 * Dining Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StartOrderingDto
 */
export interface StartOrderingDto {
    /**
     * 
     * @type {number}
     * @memberof StartOrderingDto
     */
    'tableNumber': number;
    /**
     * 
     * @type {number}
     * @memberof StartOrderingDto
     */
    'customersCount': number;
}

