/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Dining Service
 * Dining Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderingLine } from './ordering-line';
// May contain unused imports in some cases
// @ts-ignore
import type { PreparationDto } from './preparation-dto';

/**
 * 
 * @export
 * @interface TableOrder
 */
export interface TableOrder {
    /**
     * 
     * @type {string}
     * @memberof TableOrder
     */
    '_id': string;
    /**
     * 
     * @type {number}
     * @memberof TableOrder
     */
    'tableNumber': number;
    /**
     * 
     * @type {number}
     * @memberof TableOrder
     */
    'customersCount': number;
    /**
     * 
     * @type {string}
     * @memberof TableOrder
     */
    'opened': string;
    /**
     * 
     * @type {Array<OrderingLine>}
     * @memberof TableOrder
     */
    'lines': Array<OrderingLine>;
    /**
     * 
     * @type {Array<PreparationDto>}
     * @memberof TableOrder
     */
    'preparations': Array<PreparationDto>;
    /**
     * 
     * @type {string}
     * @memberof TableOrder
     */
    'billed': string;
}

