/* tslint:disable */
/* eslint-disable */
/**
 * Micro-Service Restaurant: Dining Service
 * Dining Service Open API definition
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TableWithOrderDto
 */
export interface TableWithOrderDto {
    /**
     * 
     * @type {string}
     * @memberof TableWithOrderDto
     */
    '_id': string;
    /**
     * 
     * @type {number}
     * @memberof TableWithOrderDto
     */
    'number': number;
    /**
     * 
     * @type {boolean}
     * @memberof TableWithOrderDto
     */
    'taken': boolean;
    /**
     * 
     * @type {string}
     * @memberof TableWithOrderDto
     */
    'tableOrderId': string;
}

