apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/spos/ordering
    newName: ghcr.io/startupnationlabs/spos/ordering
    newTag: sha-29921f0


patches:
  - target:
      kind: Ingress
      name: ingress-ordering
    path: ingress-patch.yml
  - target:
      kind: Deployment
      name: ordering
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: http://backend-bff.spos-dev.svc.cluster.local:3000
