/* tslint:disable */
/* eslint-disable */
/**
 * BFF API
 * Backend For Frontend API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AnnotatedMonsieurAxelMenvoie } from '../models';
// @ts-ignore
import type { AnnotatedPreparedItemAggregate } from '../models';
// @ts-ignore
import type { OrderSummary } from '../models';
/**
 * RemoteKitchenApi - axios parameter creator
 * @export
 */
export const RemoteKitchenApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerGetOrdersByGroupId: async (groupId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('remoteKitchenControllerGetOrdersByGroupId', 'groupId', groupId)
            const localVarPath = `/api/remoteKitchen/getOrdersByGroupId`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (groupId !== undefined) {
                localVarQueryParameter['groupId'] = groupId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerHandleNotServedPreparations: async (requestBody: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('remoteKitchenControllerHandleNotServedPreparations', 'requestBody', requestBody)
            const localVarPath = `/api/remoteKitchen/handleNotServedPreparations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} preparationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerPreparationDetails: async (preparationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'preparationId' is not null or undefined
            assertParamExists('remoteKitchenControllerPreparationDetails', 'preparationId', preparationId)
            const localVarPath = `/api/remoteKitchen/preparationDetails`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (preparationId !== undefined) {
                localVarQueryParameter['preparationId'] = preparationId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerReadyPreparations: async (requestBody: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('remoteKitchenControllerReadyPreparations', 'requestBody', requestBody)
            const localVarPath = `/api/remoteKitchen/readyPreparations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {AnnotatedMonsieurAxelMenvoie} annotatedMonsieurAxelMenvoie 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerSendToKitchen: async (annotatedMonsieurAxelMenvoie: AnnotatedMonsieurAxelMenvoie, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'annotatedMonsieurAxelMenvoie' is not null or undefined
            assertParamExists('remoteKitchenControllerSendToKitchen', 'annotatedMonsieurAxelMenvoie', annotatedMonsieurAxelMenvoie)
            const localVarPath = `/api/remoteKitchen/sendToKitchen`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(annotatedMonsieurAxelMenvoie, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerServePreparation: async (requestBody: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('remoteKitchenControllerServePreparation', 'requestBody', requestBody)
            const localVarPath = `/api/remoteKitchen/serve`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerStartAndFinishPreparation: async (body: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('remoteKitchenControllerStartAndFinishPreparation', 'body', body)
            const localVarPath = `/api/remoteKitchen/startAndFinishPreparation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RemoteKitchenApi - functional programming interface
 * @export
 */
export const RemoteKitchenApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RemoteKitchenApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remoteKitchenControllerGetOrdersByGroupId(groupId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrderSummary>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remoteKitchenControllerGetOrdersByGroupId(groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteKitchenApi.remoteKitchenControllerGetOrdersByGroupId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remoteKitchenControllerHandleNotServedPreparations(requestBody: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remoteKitchenControllerHandleNotServedPreparations(requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteKitchenApi.remoteKitchenControllerHandleNotServedPreparations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} preparationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remoteKitchenControllerPreparationDetails(preparationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AnnotatedPreparedItemAggregate>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remoteKitchenControllerPreparationDetails(preparationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteKitchenApi.remoteKitchenControllerPreparationDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remoteKitchenControllerReadyPreparations(requestBody: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remoteKitchenControllerReadyPreparations(requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteKitchenApi.remoteKitchenControllerReadyPreparations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {AnnotatedMonsieurAxelMenvoie} annotatedMonsieurAxelMenvoie 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remoteKitchenControllerSendToKitchen(annotatedMonsieurAxelMenvoie: AnnotatedMonsieurAxelMenvoie, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remoteKitchenControllerSendToKitchen(annotatedMonsieurAxelMenvoie, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteKitchenApi.remoteKitchenControllerSendToKitchen']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remoteKitchenControllerServePreparation(requestBody: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remoteKitchenControllerServePreparation(requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteKitchenApi.remoteKitchenControllerServePreparation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remoteKitchenControllerStartAndFinishPreparation(body: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.remoteKitchenControllerStartAndFinishPreparation(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteKitchenApi.remoteKitchenControllerStartAndFinishPreparation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RemoteKitchenApi - factory interface
 * @export
 */
export const RemoteKitchenApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RemoteKitchenApiFp(configuration)
    return {
        /**
         * 
         * @param {RemoteKitchenApiRemoteKitchenControllerGetOrdersByGroupIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerGetOrdersByGroupId(requestParameters: RemoteKitchenApiRemoteKitchenControllerGetOrdersByGroupIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<OrderSummary> {
            return localVarFp.remoteKitchenControllerGetOrdersByGroupId(requestParameters.groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RemoteKitchenApiRemoteKitchenControllerHandleNotServedPreparationsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerHandleNotServedPreparations(requestParameters: RemoteKitchenApiRemoteKitchenControllerHandleNotServedPreparationsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.remoteKitchenControllerHandleNotServedPreparations(requestParameters.requestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RemoteKitchenApiRemoteKitchenControllerPreparationDetailsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerPreparationDetails(requestParameters: RemoteKitchenApiRemoteKitchenControllerPreparationDetailsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<AnnotatedPreparedItemAggregate>> {
            return localVarFp.remoteKitchenControllerPreparationDetails(requestParameters.preparationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RemoteKitchenApiRemoteKitchenControllerReadyPreparationsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerReadyPreparations(requestParameters: RemoteKitchenApiRemoteKitchenControllerReadyPreparationsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.remoteKitchenControllerReadyPreparations(requestParameters.requestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RemoteKitchenApiRemoteKitchenControllerSendToKitchenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerSendToKitchen(requestParameters: RemoteKitchenApiRemoteKitchenControllerSendToKitchenRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.remoteKitchenControllerSendToKitchen(requestParameters.annotatedMonsieurAxelMenvoie, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RemoteKitchenApiRemoteKitchenControllerServePreparationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerServePreparation(requestParameters: RemoteKitchenApiRemoteKitchenControllerServePreparationRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.remoteKitchenControllerServePreparation(requestParameters.requestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RemoteKitchenApiRemoteKitchenControllerStartAndFinishPreparationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remoteKitchenControllerStartAndFinishPreparation(requestParameters: RemoteKitchenApiRemoteKitchenControllerStartAndFinishPreparationRequest, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.remoteKitchenControllerStartAndFinishPreparation(requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for remoteKitchenControllerGetOrdersByGroupId operation in RemoteKitchenApi.
 * @export
 * @interface RemoteKitchenApiRemoteKitchenControllerGetOrdersByGroupIdRequest
 */
export interface RemoteKitchenApiRemoteKitchenControllerGetOrdersByGroupIdRequest {
    /**
     * 
     * @type {string}
     * @memberof RemoteKitchenApiRemoteKitchenControllerGetOrdersByGroupId
     */
    readonly groupId: string
}

/**
 * Request parameters for remoteKitchenControllerHandleNotServedPreparations operation in RemoteKitchenApi.
 * @export
 * @interface RemoteKitchenApiRemoteKitchenControllerHandleNotServedPreparationsRequest
 */
export interface RemoteKitchenApiRemoteKitchenControllerHandleNotServedPreparationsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof RemoteKitchenApiRemoteKitchenControllerHandleNotServedPreparations
     */
    readonly requestBody: Array<string>
}

/**
 * Request parameters for remoteKitchenControllerPreparationDetails operation in RemoteKitchenApi.
 * @export
 * @interface RemoteKitchenApiRemoteKitchenControllerPreparationDetailsRequest
 */
export interface RemoteKitchenApiRemoteKitchenControllerPreparationDetailsRequest {
    /**
     * 
     * @type {string}
     * @memberof RemoteKitchenApiRemoteKitchenControllerPreparationDetails
     */
    readonly preparationId: string
}

/**
 * Request parameters for remoteKitchenControllerReadyPreparations operation in RemoteKitchenApi.
 * @export
 * @interface RemoteKitchenApiRemoteKitchenControllerReadyPreparationsRequest
 */
export interface RemoteKitchenApiRemoteKitchenControllerReadyPreparationsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof RemoteKitchenApiRemoteKitchenControllerReadyPreparations
     */
    readonly requestBody: Array<string>
}

/**
 * Request parameters for remoteKitchenControllerSendToKitchen operation in RemoteKitchenApi.
 * @export
 * @interface RemoteKitchenApiRemoteKitchenControllerSendToKitchenRequest
 */
export interface RemoteKitchenApiRemoteKitchenControllerSendToKitchenRequest {
    /**
     * 
     * @type {AnnotatedMonsieurAxelMenvoie}
     * @memberof RemoteKitchenApiRemoteKitchenControllerSendToKitchen
     */
    readonly annotatedMonsieurAxelMenvoie: AnnotatedMonsieurAxelMenvoie
}

/**
 * Request parameters for remoteKitchenControllerServePreparation operation in RemoteKitchenApi.
 * @export
 * @interface RemoteKitchenApiRemoteKitchenControllerServePreparationRequest
 */
export interface RemoteKitchenApiRemoteKitchenControllerServePreparationRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof RemoteKitchenApiRemoteKitchenControllerServePreparation
     */
    readonly requestBody: Array<string>
}

/**
 * Request parameters for remoteKitchenControllerStartAndFinishPreparation operation in RemoteKitchenApi.
 * @export
 * @interface RemoteKitchenApiRemoteKitchenControllerStartAndFinishPreparationRequest
 */
export interface RemoteKitchenApiRemoteKitchenControllerStartAndFinishPreparationRequest {
    /**
     * 
     * @type {string}
     * @memberof RemoteKitchenApiRemoteKitchenControllerStartAndFinishPreparation
     */
    readonly body: string
}

/**
 * RemoteKitchenApi - object-oriented interface
 * @export
 * @class RemoteKitchenApi
 * @extends {BaseAPI}
 */
export class RemoteKitchenApi extends BaseAPI {
    /**
     * 
     * @param {RemoteKitchenApiRemoteKitchenControllerGetOrdersByGroupIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RemoteKitchenApi
     */
    public remoteKitchenControllerGetOrdersByGroupId(requestParameters: RemoteKitchenApiRemoteKitchenControllerGetOrdersByGroupIdRequest, options?: RawAxiosRequestConfig) {
        return RemoteKitchenApiFp(this.configuration).remoteKitchenControllerGetOrdersByGroupId(requestParameters.groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RemoteKitchenApiRemoteKitchenControllerHandleNotServedPreparationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RemoteKitchenApi
     */
    public remoteKitchenControllerHandleNotServedPreparations(requestParameters: RemoteKitchenApiRemoteKitchenControllerHandleNotServedPreparationsRequest, options?: RawAxiosRequestConfig) {
        return RemoteKitchenApiFp(this.configuration).remoteKitchenControllerHandleNotServedPreparations(requestParameters.requestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RemoteKitchenApiRemoteKitchenControllerPreparationDetailsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RemoteKitchenApi
     */
    public remoteKitchenControllerPreparationDetails(requestParameters: RemoteKitchenApiRemoteKitchenControllerPreparationDetailsRequest, options?: RawAxiosRequestConfig) {
        return RemoteKitchenApiFp(this.configuration).remoteKitchenControllerPreparationDetails(requestParameters.preparationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RemoteKitchenApiRemoteKitchenControllerReadyPreparationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RemoteKitchenApi
     */
    public remoteKitchenControllerReadyPreparations(requestParameters: RemoteKitchenApiRemoteKitchenControllerReadyPreparationsRequest, options?: RawAxiosRequestConfig) {
        return RemoteKitchenApiFp(this.configuration).remoteKitchenControllerReadyPreparations(requestParameters.requestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RemoteKitchenApiRemoteKitchenControllerSendToKitchenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RemoteKitchenApi
     */
    public remoteKitchenControllerSendToKitchen(requestParameters: RemoteKitchenApiRemoteKitchenControllerSendToKitchenRequest, options?: RawAxiosRequestConfig) {
        return RemoteKitchenApiFp(this.configuration).remoteKitchenControllerSendToKitchen(requestParameters.annotatedMonsieurAxelMenvoie, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RemoteKitchenApiRemoteKitchenControllerServePreparationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RemoteKitchenApi
     */
    public remoteKitchenControllerServePreparation(requestParameters: RemoteKitchenApiRemoteKitchenControllerServePreparationRequest, options?: RawAxiosRequestConfig) {
        return RemoteKitchenApiFp(this.configuration).remoteKitchenControllerServePreparation(requestParameters.requestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RemoteKitchenApiRemoteKitchenControllerStartAndFinishPreparationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RemoteKitchenApi
     */
    public remoteKitchenControllerStartAndFinishPreparation(requestParameters: RemoteKitchenApiRemoteKitchenControllerStartAndFinishPreparationRequest, options?: RawAxiosRequestConfig) {
        return RemoteKitchenApiFp(this.configuration).remoteKitchenControllerStartAndFinishPreparation(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}

