apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: payment-sharing
  name: payment-sharing
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-sharing
  template:
    metadata:
      labels:
        io.kompose.service: payment-sharing
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/spos/payment-sharing:sha-bcc8181
          name: payment-sharing
          ports:
            - containerPort: 3002
              protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: BACKEND_BFF_URL
              value: "http://backend-bff.spos-dev.svc.cluster.local:3000"
      restartPolicy: Always
