apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/spos/frontend-common-space
    newName: ghcr.io/startupnationlabs/spos/frontend-common-space
    newTag: sha-fea3f18

patches:
  - target:
      kind: Ingress
      name: ingress-frontend-common-space
    path: ingress-patch.yml
