apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/spos/backend-bff
    newName: ghcr.io/startupnationlabs/spos/backend-bff
    newTag: sha-5d26c64


patches:
  - target:
      kind: Ingress
      name: ingress-backend-bff
    path: ingress-patch.yml
