apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ordering
  name: ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ordering
  template:
    metadata:
      labels:
        io.kompose.service: ordering
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/spos/ordering:sha-bcc8181
          name: ordering
          ports:
            - containerPort: 3003
              protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: GROUP_API_BASE_PATH
              value: "http://backend-bff.spos-dev.svc.cluster.local:3000"
            - name: DINING_API_BASE_PATH
              value: "http://dining-backend.spos-prod.svc.cluster.local:3000"
            - name: MENU_API_BASE_PATH
              value: "http://menu-backend.spos-prod.svc.cluster.local:3000"
            - name: OTLP_URL
              value: "http://jaeger-collector:4318/v1/traces"
      restartPolicy: Always
