/* tslint:disable */
/* eslint-disable */
/**
 * Payment Sharing API
 * Payment Sharing API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ItemRequestDto
 */
export interface ItemRequestDto {
    /**
     * 
     * @type {string}
     * @memberof ItemRequestDto
     */
    'group_id': string;
    /**
     * 
     * @type {string}
     * @memberof ItemRequestDto
     */
    'owner_id': string;
    /**
     * 
     * @type {string}
     * @memberof ItemRequestDto
     */
    'item_short_name': string;
    /**
     * 
     * @type {number}
     * @memberof ItemRequestDto
     */
    'amount': number;
    /**
     * 
     * @type {string}
     * @memberof ItemRequestDto
     */
    'table_id': string;
}

