/* tslint:disable */
/* eslint-disable */
/**
 * Payment Sharing API
 * Payment Sharing API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaymentResponseItemDetailsDTO } from './payment-response-item-details-dto';

/**
 * 
 * @export
 * @interface PaymentResponseItemDTO
 */
export interface PaymentResponseItemDTO {
    /**
     * 
     * @type {PaymentResponseItemDetailsDTO}
     * @memberof PaymentResponseItemDTO
     */
    'item': PaymentResponseItemDetailsDTO;
    /**
     * 
     * @type {number}
     * @memberof PaymentResponseItemDTO
     */
    'onTable': number;
    /**
     * 
     * @type {number}
     * @memberof PaymentResponseItemDTO
     */
    'remaining': number;
}

