/* tslint:disable */
/* eslint-disable */
/**
 * Payment Sharing API
 * Payment Sharing API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentResponseItemDetailsDTO
 */
export interface PaymentResponseItemDetailsDTO {
    /**
     * 
     * @type {string}
     * @memberof PaymentResponseItemDetailsDTO
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof PaymentResponseItemDetailsDTO
     */
    'price': number;
    /**
     * 
     * @type {string}
     * @memberof PaymentResponseItemDetailsDTO
     */
    'id': string;
}

