/* tslint:disable */
/* eslint-disable */
/**
 * Payment Sharing API
 * Payment Sharing API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SelectedItemDTO } from './selected-item-dto';

/**
 * 
 * @export
 * @interface SelectedByCustomerDTO
 */
export interface SelectedByCustomerDTO {
    /**
     * 
     * @type {number}
     * @memberof SelectedByCustomerDTO
     */
    'number': number;
    /**
     * 
     * @type {Array<SelectedItemDTO>}
     * @memberof SelectedByCustomerDTO
     */
    'elements': Array<SelectedItemDTO>;
}

