/* tslint:disable */
/* eslint-disable */
/**
 * Ordering API
 * Ordering API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CartItem
 */
export interface CartItem {
    /**
     * 
     * @type {string}
     * @memberof CartItem
     */
    'itemId': string;
    /**
     * 
     * @type {string}
     * @memberof CartItem
     */
    'shortName': string;
    /**
     * 
     * @type {number}
     * @memberof CartItem
     */
    'quantity': number;
}

