/* tslint:disable */
/* eslint-disable */
/**
 * Ordering API
 * Ordering API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CartItem } from './cart-item';

/**
 * 
 * @export
 * @interface OrderingRequestDTO
 */
export interface OrderingRequestDTO {
    /**
     * 
     * @type {Array<CartItem>}
     * @memberof OrderingRequestDTO
     */
    'cart': Array<CartItem>;
    /**
     * 
     * @type {string}
     * @memberof OrderingRequestDTO
     */
    'groupId': string;
    /**
     * 
     * @type {number}
     * @memberof OrderingRequestDTO
     */
    'tableNumber': number;
}

